version: "3"

services:
  mysql: 
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: chat_test
      MYSQL_USER: test
    ports:
      - "3306:3306"
    volumes:
      - .docker/mysql/data:/var/lib/mysql